python:
  - 2.7
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
install:
  - sudo pip install -U pip pip-tools
  - sudo pip-compile
  - sudo pip install -r requirements.txt
script:
  - python --version
  - ./test_run.sh
