language: python
python:
  - 3.5
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
install:
  - pip install -U pip pip-tools
  - pip-compile
  - pip install -r requirements.txt
script:
  - python --version
  - ./test_run.sh
